location = /magazin/laborcontainer-genehmigung-bauantrag { return 301 https://planexus.de/magazin/laborcontainer-genehmigung-baurecht-vorschriften; }
location = /magazin/laborcontainer-genehmigung-bauantrag/ { return 301 https://planexus.de/magazin/laborcontainer-genehmigung-baurecht-vorschriften; }
location = /home { return 301 https://planexus.de/; }
location = /home/ { return 301 https://planexus.de/; }
location = /labtogo { return 301 https://planexus.de/laborcontainer/labtogo; }
location = /labtogo/ { return 301 https://planexus.de/laborcontainer/labtogo; }
# location = /team/thomas-boss { return 301 https://planexus.de/team; }
# location = /team/thomas-boss/ { return 301 https://planexus.de/team; }
# location = /team/sven-biewald { return 301 https://planexus.de/team; }
# location = /team/sven-biewald/ { return 301 https://planexus.de/team; }
location = /team/dan-smith { return 301 https://planexus.de/team; }
location = /team/dan-smith/ { return 301 https://planexus.de/team; }
location = /category/business { return 301 https://planexus.de/magazin; }
location = /category/business/ { return 301 https://planexus.de/magazin; }
location = /category/ai { return 301 https://planexus.de/magazin; }
location = /category/ai/ { return 301 https://planexus.de/magazin; }
location = /sitemap.xml { return 301 https://planexus.de/sitemap-index.xml; }
location = /sitemap.xml/ { return 301 https://planexus.de/sitemap-index.xml; }
location = /about { return 301 https://planexus.de/ueber-uns; }
location = /about/ { return 301 https://planexus.de/ueber-uns; }
location = /services { return 301 https://planexus.de/leistungen; }
location = /services/ { return 301 https://planexus.de/leistungen; }
location = /contact { return 301 https://planexus.de/kontakt; }
location = /contact/ { return 301 https://planexus.de/kontakt; }
location = /products { return 301 https://planexus.de/laborcontainer; }
location = /products/ { return 301 https://planexus.de/laborcontainer; }
location ~* ^/wp- { return 410; }
location = /xmlrpc.php { return 410; }
