uploads = []

[[generated]]
id = "9HYocX5nchf4Wq_TemdaS"
uri = "file://public/images/blog-laborcontainer-katastropheneinsatz.png"
type = "image"
title = "generated_image"

[[outputs]]
id = "BuMIqmxvXTqQLNbeIhXhL"
uri = "file://public/images/blog-laborcontainer-katastropheneinsatz.png"
type = "image"
title = "Blog-Bild: Laborcontainer im Katastropheneinsatz"

[[outputs]]
id = "ckBckbCI-0LxD7c9JBxE-"
uri = "file://Money-Page-Recherche.md"
type = "text"
title = "Money-Page Recherche & Bauplan"

[[outputs]]
id = "ba4SLKGQKXbcybZIrqrc8"
uri = "file://Bauplan-Staedteseiten.md"
type = "text"
title = "Bauplan: Städteseiten als Money Pages"
